### ISSUE TITLE
checkablechipview contains references to both AndroidX and old support library

### ISSUE THREAD

**Issue by jrcacd** [okdroid/checkable-chip-view#28] opened 2020-12-08 15:00 UTC
WARNING: [Processor] Library 'C:\Users\aaa\.gradle\caches\modules-2\files-2.1\com.github.okdroid\checkablechipview\1.0.2\c5804934c3754214b7881f1cf60216faebecc4af\checkablechipview-1.0.2.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated.

**Comment by markushi** [comment] 2020-12-09 06:03
Duplicate of #26, please use version `2.0.0`

**Closed as completed by markushi** 2020-12-09 06:03 UTC

**Comment by jrcacd** [comment] 2020-12-09 08:28
Ok, thanks
